config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users, only: %i(new create edit update) do
    resources :items, only: %i(index)
  end

  resources :items

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 60 }
  validates :description, presence: true
  validates :category, presence: true, format: { with: /\A[a-zA-Z ]*\z/, message: "may only contain letters and spaces" }

  def self.all_categories
    Item.pluck("DISTINCT category")
  end
end

app/models/user.rb
require "digest/sha1"

class User < ApplicationRecord
  before_save do
    hash_password if needs_password_update?
  end

  has_many :items

  validates :username, uniqueness: true, length: { minimum: 4 }
  validates :email, format: { with: /@/, message: "has to look like an email address" }
  validates :password, confirmation: true, presence: true, if: ->{ needs_password_update? }
  validates :password_confirmation, presence: true, if: ->{ needs_password_update? }

  private

  def needs_password_update?
    new_record? || (password_changed? && !password.blank?)
  end

  def hash_password
    self.password = Digest::SHA1.hexdigest self.password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    unless current_user
      flash[:error] = "The requested page was not found"
      redirect_to "/" unless current_user
    end
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find_by(id: session[:user_id])

    render :index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    render :new
  end

  def create
    item = current_user.items.new(item_params)

    if item.save
      flash[:notice] = "Item \"#{item.name}\" was created successfully"
      redirect_to "/"
    else
      @item = item
      flash[:errors] = item.errors.full_messages
      render :new
    end
  end

  def index
    @items = current_user.items
    render "user_items"
  end

  def edit
    @item = current_user.items.find_by(id: params[:id])

    if @item
      render :edit
    else
      flash[:error] = "Item not found"
      redirect_to "/"
    end
  end

  def update
    item = current_user.items.find_by(params[:id])

    if item.update(item_params)
      flash[:success] = "The item details have been saved"
      redirect_to user_items_path(current_user)
    else
      @item = item
      flash[:errors] = item.errors.full_messages
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category)
  end
end

app/controllers/sessions_controller.rb
require "digest/sha1"

class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by(username: params[:username], password: Digest::SHA1.hexdigest(params[:password]))

    if user
      session[:user_id] = user.id
      redirect_to "/"
    else
      flash.now[:error] = "User not found"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

  private

  def session_params
    params.require(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i(new create)

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)

    if user.save
      flash[:notice] = "User has been created successfully!"
      redirect_to "/"
    else
      @user = User.new
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if user_params[:password].blank?
      params[:user].delete(:password)
    end

    if current_user.update(user_params)
      flash.now[:success] = "User details updated"
      render :edit
    else
      flash.now[:errors] = current_user.errors.full_messages
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_not_logged_in.html.erb
<%= link_to "Create user", new_user_path %><br />
<%= link_to "Log in", login_path %>

app/views/home/_welcome.html.erb
<h2>
  Welcome <%= user.username %>!
</h2>

<%= link_to "Profile", edit_user_path(@user) %><br />
<%= link_to "My Item listing", user_items_path(@user) %><br />
<%= link_to "Log out", logout_path %>

app/views/home/index.html.erb
<div id="main_page">
  <% if @user %>
    <%= render "welcome", user: @user %>
  <% else %>
    <%= render "not_logged_in" %>
  <% end %>
</div>

app/views/items/edit.html.erb
<%
  opts = [["New Category", "new_category"]]
  opts << ["---", "---"]
  Item.all_categories.each { |cat| opts << [cat, cat] }
%>

<h2>
  Edit item!
</h2>

<div class="form" id="new_item_form">
  <%= form_for @item do |form| %>
    <%= field_set_tag "Edit item details" do %>
      <%= render "shared/form_errors" %>

      <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.label :description %>
        <%= form.text_area :description %>
      </p>

      <p>
        <%= form.label :category %>
        <%= form.select(:category, options_for_select(opts, disabled: "---", selected: @item.category), {}, id: "category_dropdown", onchange: "onChangeCategoryDropdown()") %>
      </p>

      <p id="new_category">
        <%= form.label "New category" %>
        <%= form.text_field :category, value: "", disabled: true %>
      </p>

      <p>
        <%= form.submit "Save" %>
      </p>
    <% end %>
  <% end %>
  <div class="clear"></div>

</div>

app/views/items/new.html.erb
<%
  opts = [["New Category", "new_category"]]
  opts << ["---", "---"]
  Item.all_categories.each { |cat| opts << [cat, cat] }
%>

<h2>
  Create new item!
</h2>

<div class="form" id="new_item_form">
  <%= form_for @item do |form| %>
    <%= field_set_tag "New item details" do %>
      <%= render "shared/form_errors" %>

      <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.label :description %>
        <%= form.text_area :description %>
      </p>

      <p>
        <%= form.label :category %>
        <%= form.select(:category, options_for_select(opts, disabled: "---")) %>
      </p>

      <p>
        <%= form.submit "Create" %>
      </p>
    <% end %>
  <% end %>
  <div class="clear"></div>

</div>

app/views/items/user_items.html.erb
<h2>My listing</h2>

<%= link_to "Add new item", new_item_path %>

<div id="user_items">
  <% @items.each do |item| %>
    <div class="item">
      <p class="name"><%= item.name %></p>
      <p class="description"><%= item.description %></p>
      <p class="category"><%= item.category %></p>
      <p><%= link_to "Edit item", edit_item_path(item) %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QaTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
  </head>

  <style type="text/css">
    h1 a {
      text-decoration: none;
      color: black;
    }
  </style>


  <body>
    <h1><a href="/">Qa Test Page</a></h1>

    <div id="flash">
      <%= render "shared/flash" %>
    </div>

    <div id="main_content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="success">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="error">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if flash[:errors] %>
  <div class="error">
    <ul class="errors">
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>
  Edit user details
</h2>

<div class="form" id="profile_form">
  <%= form_for @user do |form| %>
    <%= field_set_tag "Edit user details" do %>
      <%= render "shared/form_errors" %>

      <p>
        <%= form.label :username %>
        <%= form.text_field :username %>
      </p>

      <p>
        <%= form.label :email %>
        <%= form.text_field :email %><br />
      </p>

      <p>
        <%= form.label :password %>
        <%= form.password_field :password %><br />
      </p>

      <p>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %><br />
      </p>

      <p>
        <%= form.submit "Save" %>
      </p>
    <% end %>
  <% end %>
  <div class="clear"></div>

</div>

app/views/users/new.html.erb
<h2>
  Create user
</h2>



<div class="form" id="signup_form">
  <%= form_for @user do |form| %>
    <%= field_set_tag "New user details" do %>
      <%= render "shared/form_errors" %>

      <p>
        <%= form.label :username %>
        <%= form.text_field :username %>
      </p>

      <p>
        <%= form.label :email %>
        <%= form.text_field :email %><br />
      </p>

      <p>
        <%= form.label :password %>
        <%= form.password_field :password %><br />
      </p>

      <p>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %><br />
      </p>

      <p>
        <%= form.submit "Create" %>
      </p>
    <% end %>
  <% end %>
  <div class="clear"></div>

</div>